import { FileText, Lightbulb } from "lucide-react";

import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import type { IncidentReport } from "@/types";

export function IncidentReportCard({ report }: { report: IncidentReport }) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <FileText className="size-4 text-muted-foreground" />
          <CardTitle className="text-lg">Incident report</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm">{report.summary}</p>
        {report.recommendations.length > 0 && (
          <div>
            <div className="mb-2 text-xs uppercase tracking-wider text-muted-foreground">
              Recommendations
            </div>
            <ul className="space-y-1.5">
              {report.recommendations.map((r) => (
                <li key={r} className="flex items-start gap-2 text-sm">
                  <Lightbulb className="mt-0.5 size-4 shrink-0 text-amber-600 dark:text-amber-400" />
                  <span>{r}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </CardContent>
      <CardFooter className="text-xs text-muted-foreground">
        Generated by {report.model} at {new Date(report.timestamp).toLocaleString()}
      </CardFooter>
    </Card>
  );
}
